[project]
name = "cyberpunk_blog_backend"
version = "0.1.0"
description = "REEP's CyberPunk Blog Backend"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.1",
    "psycopg2>=2.9.10",
]
